### ISSUE TITLE
Per-user settings

### ISSUE THREAD

**Issue by gianlucagiacometti** [Offerel/roundcube_elasticext#5]
Hi,
I think this is a pretty good idea. It would be much more usable in big organisations if it the setting were designed on a per-user basis.

**Comment by Offerel** [comment]
Ok. But it is only useful for the editor part. Because the login feature is bound to no user interaction. This depends only by the selected main skin.

**Comment by gianlucagiacometti** [comment]
Well, I mean the position of the send button. It can be useful, but from my experience it's not nice to force a change globally.
