### ISSUE TITLE
How to install? Any guides?

### ISSUE THREAD

**Issue by emirefek** [Offerel/roundcube_elasticext#7]
How to install? Any guides?
Is it native coded plugin/extended skin or just drag&drop gimmick file base?

**Comment by Offerel** [comment]
You can install this addon via the standard way, like every other addon. Download the release tarball, extract the addon to the roundcube plugins folder. The folder should have the name "elasticext". Afterwards, add the addon with the same name to the plugin array in your roundcube config file.

Optionally, you can enable/disable the login screen function in config.inc.php in the plugin folder. The button_alignment option is only a default option and can be disabled by the logged in user in roundcube itself.
